export interface CachedSpecies {
  species: string;
  common_name: string;
  confidence: number;
  grain: string;
  hardness: string;
  color_description: string;
  common_uses: string[];
  fun_fact: string;
  origin: string;
  rot_resistant: boolean;
  keywords: string[];
}

export const SPECIES_CACHE: CachedSpecies[] = [
  // ── Common Domestic ──────────────────────────────────────────────────────────
  {
    species: 'Quercus robur',
    common_name: 'English Oak',
    confidence: 72,
    grain: 'Coarse, straight to slightly interlocked',
    hardness: 'Hard (1120 lbf Janka)',
    color_description: 'Light to medium brown with a golden hue, prominent ray fleck',
    common_uses: ['Furniture', 'Flooring', 'Barrels', 'Boat building', 'Cabinetry'],
    fun_fact: 'English Oak was the primary timber for the British Royal Navy — a single warship required over 2,000 mature oak trees.',
    origin: 'Europe, Western Asia',
    rot_resistant: true,
    keywords: ['brown', 'tan', 'golden', 'straight grain', 'ring porous', 'oak', 'coarse', 'ray fleck', 'english oak'],
  },
  {
    species: 'Acer saccharum',
    common_name: 'Sugar Maple',
    confidence: 72,
    grain: 'Fine, straight to wavy',
    hardness: 'Very Hard (1450 lbf Janka)',
    color_description: 'Creamy white to light reddish-brown, often with subtle figure',
    common_uses: ['Flooring', 'Bowling alleys', 'Butcher blocks', 'Musical instruments', 'Furniture'],
    fun_fact: 'Sugar Maple is the source of maple syrup — it takes about 40 gallons of sap to produce just one gallon of syrup.',
    origin: 'Eastern North America',
    rot_resistant: false,
    keywords: ['white', 'cream', 'light brown', 'fine grain', 'maple', 'hard maple', 'smooth', 'diffuse porous'],
  },
  {
    species: 'Juglans nigra',
    common_name: 'Black Walnut',
    confidence: 72,
    grain: 'Straight to slightly wavy',
    hardness: 'Hard (1010 lbf Janka)',
    color_description: 'Rich chocolate brown to dark purplish-brown, lighter sapwood',
    common_uses: ['Fine furniture', 'Gun stocks', 'Cabinetry', 'Veneer', 'Turning'],
    fun_fact: 'Black Walnut produces juglone, a chemical that is toxic to many plants — nothing grows well beneath a walnut tree.',
    origin: 'Eastern North America',
    rot_resistant: true,
    keywords: ['dark brown', 'chocolate', 'purple', 'walnut', 'black walnut', 'straight grain', 'rich'],
  },
  {
    species: 'Prunus serotina',
    common_name: 'Black Cherry',
    confidence: 72,
    grain: 'Fine, straight to slightly wavy',
    hardness: 'Medium-Hard (950 lbf Janka)',
    color_description: 'Light pinkish-brown when fresh, deepens to rich reddish-brown with age',
    common_uses: ['Fine furniture', 'Cabinetry', 'Veneer', 'Musical instruments', 'Flooring'],
    fun_fact: 'Black Cherry darkens dramatically with UV exposure — pieces left in sunlight for just a few weeks develop a rich, warm patina.',
    origin: 'Eastern North America',
    rot_resistant: false,
    keywords: ['pink', 'reddish brown', 'cherry', 'fine grain', 'smooth', 'warm', 'light'],
  },
  {
    species: 'Pinus strobus',
    common_name: 'Eastern White Pine',
    confidence: 72,
    grain: 'Fine, straight',
    hardness: 'Soft (380 lbf Janka)',
    color_description: 'Pale yellow to light brown, resinous with visible growth rings',
    common_uses: ['Construction', 'Millwork', 'Furniture', 'Carving', 'Paneling'],
    fun_fact: 'Eastern White Pine was so prized by the British Crown that the tallest trees were marked with a broad arrow and reserved for Royal Navy masts.',
    origin: 'Eastern North America',
    rot_resistant: false,
    keywords: ['pale', 'yellow', 'light', 'pine', 'white pine', 'soft', 'resinous', 'knots', 'straight grain'],
  },
  {
    species: 'Fraxinus americana',
    common_name: 'White Ash',
    confidence: 72,
    grain: 'Coarse, straight',
    hardness: 'Hard (1320 lbf Janka)',
    color_description: 'Light to medium brown, sometimes with an olive hue, prominent growth rings',
    common_uses: ['Baseball bats', 'Tool handles', 'Flooring', 'Furniture', 'Oars'],
    fun_fact: 'White Ash is the traditional wood for Major League Baseball bats — its combination of strength, flexibility, and light weight is unmatched.',
    origin: 'Eastern North America',
    rot_resistant: false,
    keywords: ['light brown', 'tan', 'ash', 'white ash', 'coarse', 'ring porous', 'straight', 'olive'],
  },
  {
    species: 'Betula alleghaniensis',
    common_name: 'Yellow Birch',
    confidence: 72,
    grain: 'Fine, straight to wavy',
    hardness: 'Hard (1260 lbf Janka)',
    color_description: 'Light reddish-brown heartwood, pale yellowish-white sapwood',
    common_uses: ['Furniture', 'Cabinetry', 'Flooring', 'Plywood', 'Turned objects'],
    fun_fact: 'Yellow Birch bark has a distinctive wintergreen scent when scratched — the tree was historically used to make birch beer.',
    origin: 'Northeastern North America',
    rot_resistant: false,
    keywords: ['reddish brown', 'yellow', 'birch', 'fine grain', 'smooth', 'pale', 'light'],
  },
  {
    species: 'Populus tremuloides',
    common_name: 'Quaking Aspen',
    confidence: 72,
    grain: 'Fine, straight',
    hardness: 'Soft (350 lbf Janka)',
    color_description: 'Nearly white to pale grayish-brown, uniform and featureless',
    common_uses: ['Pulp', 'Matches', 'Chopsticks', 'Sauna benches', 'Crates'],
    fun_fact: 'A grove of Quaking Aspen in Utah called Pando is considered the largest living organism on Earth — 47,000 genetically identical trees sharing one root system.',
    origin: 'North America',
    rot_resistant: false,
    keywords: ['white', 'pale', 'gray', 'aspen', 'soft', 'fine grain', 'uniform', 'light'],
  },
  {
    species: 'Tsuga canadensis',
    common_name: 'Eastern Hemlock',
    confidence: 72,
    grain: 'Fine, uneven',
    hardness: 'Soft (500 lbf Janka)',
    color_description: 'Light reddish-brown to pale tan, often with a purplish tinge',
    common_uses: ['Construction lumber', 'Pulp', 'Tanning leather', 'Framing', 'Sheathing'],
    fun_fact: 'Eastern Hemlock bark was the primary source of tannin for the American leather industry throughout the 19th century.',
    origin: 'Eastern North America',
    rot_resistant: false,
    keywords: ['light brown', 'tan', 'hemlock', 'soft', 'fine', 'reddish', 'pale'],
  },
  {
    species: 'Liriodendron tulipifera',
    common_name: 'Tulip Poplar',
    confidence: 72,
    grain: 'Fine, straight',
    hardness: 'Soft-Medium (540 lbf Janka)',
    color_description: 'Greenish-yellow to brown, often with streaks of purple, green, or black',
    common_uses: ['Furniture', 'Cabinetry', 'Musical instruments', 'Carving', 'Millwork'],
    fun_fact: 'Despite its name, Tulip Poplar is not a true poplar — it is actually the tallest native broadleaf tree in North America, reaching over 160 feet.',
    origin: 'Eastern North America',
    rot_resistant: false,
    keywords: ['green', 'yellow', 'purple streaks', 'poplar', 'tulip poplar', 'fine grain', 'colorful'],
  },
  {
    species: 'Carya ovata',
    common_name: 'Shagbark Hickory',
    confidence: 72,
    grain: 'Straight to slightly wavy, coarse',
    hardness: 'Very Hard (1880 lbf Janka)',
    color_description: 'Tan to reddish-brown heartwood, wide pale sapwood',
    common_uses: ['Tool handles', 'Ladder rungs', 'Flooring', 'Smoking wood', 'Sporting goods'],
    fun_fact: 'Shagbark Hickory is the hardest and heaviest native North American wood — it was used for the first American-made golf club shafts.',
    origin: 'Eastern North America',
    rot_resistant: false,
    keywords: ['tan', 'reddish brown', 'hickory', 'hard', 'coarse', 'pale sapwood', 'strong'],
  },
  {
    species: 'Acer rubrum',
    common_name: 'Red Maple',
    confidence: 72,
    grain: 'Fine, straight to wavy',
    hardness: 'Medium-Hard (950 lbf Janka)',
    color_description: 'Light to medium reddish-brown, sometimes with a grayish cast',
    common_uses: ['Furniture', 'Flooring', 'Cabinetry', 'Veneer', 'Musical instruments'],
    fun_fact: 'Red Maple is the most abundant tree in eastern North America and is the first tree to flower each spring, often while snow is still on the ground.',
    origin: 'Eastern North America',
    rot_resistant: false,
    keywords: ['reddish brown', 'red', 'maple', 'soft maple', 'fine grain', 'medium', 'light'],
  },
  {
    species: 'Quercus rubra',
    common_name: 'Red Oak',
    confidence: 72,
    grain: 'Coarse, straight',
    hardness: 'Hard (1290 lbf Janka)',
    color_description: 'Pinkish to reddish-brown, prominent ray fleck on quartersawn faces',
    common_uses: ['Flooring', 'Furniture', 'Cabinetry', 'Millwork', 'Veneer'],
    fun_fact: 'Red Oak is the most commercially important hardwood in the United States — it accounts for nearly half of all hardwood lumber sold.',
    origin: 'Eastern North America',
    rot_resistant: false,
    keywords: ['pink', 'reddish', 'red oak', 'oak', 'coarse', 'ring porous', 'ray fleck', 'medium brown'],
  },
  {
    species: 'Tilia americana',
    common_name: 'American Basswood',
    confidence: 72,
    grain: 'Fine, straight',
    hardness: 'Soft (410 lbf Janka)',
    color_description: 'Creamy white to pale yellowish-brown, uniform and featureless',
    common_uses: ['Carving', 'Musical instruments', 'Beehives', 'Millwork', 'Pulp'],
    fun_fact: 'American Basswood is the preferred wood for professional wood carvers — its fine, uniform grain carves cleanly in any direction without splitting.',
    origin: 'Eastern North America',
    rot_resistant: false,
    keywords: ['white', 'cream', 'pale', 'basswood', 'linden', 'soft', 'fine grain', 'uniform'],
  },
  {
    species: 'Ulmus americana',
    common_name: 'American Elm',
    confidence: 72,
    grain: 'Interlocked, irregular',
    hardness: 'Medium-Hard (830 lbf Janka)',
    color_description: 'Light to medium reddish-brown, often with a grayish tinge',
    common_uses: ['Furniture', 'Flooring', 'Boxes', 'Crates', 'Hockey sticks'],
    fun_fact: 'American Elm\'s interlocked grain makes it nearly impossible to split — it was the wood of choice for wagon wheel hubs that had to withstand tremendous shock.',
    origin: 'Eastern North America',
    rot_resistant: false,
    keywords: ['reddish brown', 'gray', 'elm', 'interlocked', 'irregular grain', 'medium'],
  },

  // ── Exotic / Tropical ────────────────────────────────────────────────────────
  {
    species: 'Tectona grandis',
    common_name: 'Teak',
    confidence: 72,
    grain: 'Straight to wavy, coarse',
    hardness: 'Hard (1000 lbf Janka)',
    color_description: 'Golden to dark brown, oily surface with a leather-like feel',
    common_uses: ['Boat decking', 'Outdoor furniture', 'Flooring', 'Veneer', 'Countertops'],
    fun_fact: 'Teak contains natural oils that make it self-lubricating — metal fittings embedded in teak on boats stay rust-free for decades.',
    origin: 'South and Southeast Asia',
    rot_resistant: true,
    keywords: ['golden', 'brown', 'oily', 'teak', 'coarse', 'straight', 'outdoor', 'tropical'],
  },
  {
    species: 'Swietenia macrophylla',
    common_name: 'Mahogany',
    confidence: 72,
    grain: 'Straight to interlocked, medium',
    hardness: 'Medium (900 lbf Janka)',
    color_description: 'Pale pinkish-brown when fresh, deepens to rich reddish-brown',
    common_uses: ['Fine furniture', 'Cabinetry', 'Musical instruments', 'Boat building', 'Veneer'],
    fun_fact: 'Mahogany was so prized in 18th-century England that Thomas Chippendale built his entire reputation on it — virtually all his iconic furniture was made from this single species.',
    origin: 'Central and South America',
    rot_resistant: true,
    keywords: ['reddish brown', 'pink', 'mahogany', 'medium grain', 'tropical', 'fine', 'warm'],
  },
  {
    species: 'Dalbergia nigra',
    common_name: 'Brazilian Rosewood',
    confidence: 72,
    grain: 'Straight to wavy, medium',
    hardness: 'Very Hard (2790 lbf Janka)',
    color_description: 'Chocolate brown to violet-black with irregular darker streaks',
    common_uses: ['Guitar backs and sides', 'Fine furniture', 'Veneer', 'Knife handles', 'Turning'],
    fun_fact: 'Brazilian Rosewood is so endangered that it is listed on CITES Appendix I — trading it internationally without special permits is illegal worldwide.',
    origin: 'Brazil',
    rot_resistant: true,
    keywords: ['dark brown', 'chocolate', 'black', 'violet', 'rosewood', 'streaks', 'dense', 'tropical'],
  },
  {
    species: 'Peltogyne purpurea',
    common_name: 'Purpleheart',
    confidence: 72,
    grain: 'Straight to wavy, medium',
    hardness: 'Very Hard (2520 lbf Janka)',
    color_description: 'Vivid purple when freshly cut, browns to dark eggplant with age',
    common_uses: ['Furniture accents', 'Flooring', 'Turning', 'Inlays', 'Skateboard decks'],
    fun_fact: 'Purpleheart\'s vivid color comes from a compound called peltogynol — exposure to UV light gradually converts it to a darker brown-purple over time.',
    origin: 'Central and South America',
    rot_resistant: true,
    keywords: ['purple', 'violet', 'dark', 'purpleheart', 'exotic', 'tropical', 'dense', 'colorful'],
  },
  {
    species: 'Pterocarpus soyauxii',
    common_name: 'African Padauk',
    confidence: 72,
    grain: 'Straight to interlocked, coarse',
    hardness: 'Hard (1725 lbf Janka)',
    color_description: 'Vivid orange-red when fresh, fades to reddish-brown with age',
    common_uses: ['Furniture', 'Flooring', 'Turning', 'Musical instruments', 'Decorative accents'],
    fun_fact: 'African Padauk is one of the most dimensionally stable woods in the world — it barely moves with changes in humidity, making it ideal for precision instruments.',
    origin: 'Central and West Africa',
    rot_resistant: true,
    keywords: ['orange', 'red', 'padauk', 'african', 'vivid', 'bright', 'tropical', 'coarse'],
  },
  {
    species: 'Millettia laurentii',
    common_name: 'Wenge',
    confidence: 72,
    grain: 'Straight, coarse',
    hardness: 'Very Hard (1630 lbf Janka)',
    color_description: 'Very dark brown to nearly black with fine lighter streaks',
    common_uses: ['Flooring', 'Furniture', 'Veneer', 'Musical instruments', 'Cabinetry'],
    fun_fact: 'Wenge splinters are notoriously dangerous — they are nearly invisible under the skin and can cause serious infections if not removed immediately.',
    origin: 'Central Africa',
    rot_resistant: true,
    keywords: ['dark brown', 'black', 'dark', 'wenge', 'streaks', 'coarse', 'dense', 'african'],
  },
  {
    species: 'Guibourtia demeusei',
    common_name: 'Bubinga',
    confidence: 72,
    grain: 'Straight to interlocked, medium to coarse',
    hardness: 'Very Hard (2690 lbf Janka)',
    color_description: 'Pinkish-red to reddish-brown with darker purple or red veins',
    common_uses: ['Furniture', 'Veneer', 'Musical instruments', 'Turning', 'Cabinetry'],
    fun_fact: 'Bubinga is sometimes called "African Rosewood" and produces some of the most spectacular figured veneer in the world — a single slab can sell for thousands of dollars.',
    origin: 'Equatorial Africa',
    rot_resistant: true,
    keywords: ['pink', 'red', 'reddish brown', 'purple veins', 'bubinga', 'figured', 'tropical', 'dense'],
  },
  {
    species: 'Brosimum rubescens',
    common_name: 'Bloodwood',
    confidence: 72,
    grain: 'Straight to slightly interlocked, fine',
    hardness: 'Very Hard (2900 lbf Janka)',
    color_description: 'Vivid, bright red — one of the most intensely colored woods in the world',
    common_uses: ['Turning', 'Inlays', 'Accents', 'Knife handles', 'Jewelry boxes'],
    fun_fact: 'Bloodwood gets its name from the deep red sap that oozes from freshly cut surfaces — indigenous peoples of South America used it as a dye.',
    origin: 'South America',
    rot_resistant: true,
    keywords: ['red', 'bright red', 'vivid', 'bloodwood', 'tropical', 'fine grain', 'dense', 'colorful'],
  },
  {
    species: 'Diospyros crassiflora',
    common_name: 'African Ebony',
    confidence: 72,
    grain: 'Fine, straight to irregular',
    hardness: 'Extremely Hard (3000 lbf Janka)',
    color_description: 'Jet black, sometimes with faint brown or gray streaks',
    common_uses: ['Piano keys', 'Guitar fretboards', 'Knife handles', 'Turning', 'Inlays'],
    fun_fact: 'African Ebony is so dense it sinks in water — it is one of only a handful of woods with a specific gravity greater than 1.0.',
    origin: 'West and Central Africa',
    rot_resistant: true,
    keywords: ['black', 'jet black', 'dark', 'ebony', 'dense', 'fine grain', 'african', 'heavy'],
  },
  {
    species: 'Entandrophragma cylindricum',
    common_name: 'Sapele',
    confidence: 72,
    grain: 'Interlocked, producing ribbon figure on quartersawn faces',
    hardness: 'Hard (1410 lbf Janka)',
    color_description: 'Golden to dark reddish-brown with a distinctive ribbon stripe figure',
    common_uses: ['Furniture', 'Cabinetry', 'Veneer', 'Musical instruments', 'Flooring'],
    fun_fact: 'Sapele\'s interlocked grain creates a stunning ribbon stripe when quartersawn — it is one of the most visually striking veneers used in luxury car interiors.',
    origin: 'Tropical Africa',
    rot_resistant: true,
    keywords: ['reddish brown', 'golden', 'ribbon stripe', 'sapele', 'interlocked', 'figured', 'african'],
  },
  {
    species: 'Khaya anthotheca',
    common_name: 'African Mahogany',
    confidence: 72,
    grain: 'Interlocked, medium',
    hardness: 'Medium (830 lbf Janka)',
    color_description: 'Pale pinkish-brown to deep reddish-brown, often with ribbon figure',
    common_uses: ['Furniture', 'Cabinetry', 'Boat building', 'Veneer', 'Millwork'],
    fun_fact: 'African Mahogany became the primary substitute for true Honduran Mahogany after overharvesting depleted Central American forests in the 20th century.',
    origin: 'West and Central Africa',
    rot_resistant: true,
    keywords: ['pink', 'reddish brown', 'mahogany', 'african mahogany', 'medium', 'interlocked', 'tropical'],
  },
  {
    species: 'Intsia bijuga',
    common_name: 'Merbau',
    confidence: 72,
    grain: 'Interlocked, coarse',
    hardness: 'Very Hard (1925 lbf Janka)',
    color_description: 'Orange-brown to dark reddish-brown, often with yellow mineral deposits',
    common_uses: ['Flooring', 'Decking', 'Furniture', 'Boat building', 'Heavy construction'],
    fun_fact: 'Merbau contains water-soluble yellow deposits that bleed out when wet — freshly installed Merbau decking can stain concrete a vivid yellow after rain.',
    origin: 'Southeast Asia and Pacific Islands',
    rot_resistant: true,
    keywords: ['orange brown', 'reddish brown', 'merbau', 'yellow deposits', 'coarse', 'dense', 'tropical'],
  },
  {
    species: 'Eucalyptus marginata',
    common_name: 'Jarrah',
    confidence: 72,
    grain: 'Interlocked to wavy, coarse',
    hardness: 'Very Hard (1910 lbf Janka)',
    color_description: 'Rich dark red to reddish-brown, deepening with age',
    common_uses: ['Flooring', 'Furniture', 'Decking', 'Railway sleepers', 'Bridges'],
    fun_fact: 'Jarrah is naturally termite-resistant and was used for the original wooden blocks paving the streets of London in the 19th century.',
    origin: 'Western Australia',
    rot_resistant: true,
    keywords: ['dark red', 'reddish brown', 'jarrah', 'australian', 'coarse', 'dense', 'eucalyptus'],
  },
  {
    species: 'Acacia melanoxylon',
    common_name: 'Australian Blackwood',
    confidence: 72,
    grain: 'Straight to wavy, fine to medium',
    hardness: 'Hard (1160 lbf Janka)',
    color_description: 'Golden to dark brown, often with attractive fiddleback or wavy figure',
    common_uses: ['Furniture', 'Musical instruments', 'Cabinetry', 'Turning', 'Veneer'],
    fun_fact: 'Australian Blackwood is prized by luthiers as a tonal substitute for Koa — its acoustic properties make it ideal for guitar backs and sides.',
    origin: 'Australia',
    rot_resistant: true,
    keywords: ['golden', 'dark brown', 'blackwood', 'australian', 'wavy', 'figured', 'acacia'],
  },
  {
    species: 'Guaiacum officinale',
    common_name: 'Lignum Vitae',
    confidence: 72,
    grain: 'Interlocked, very fine',
    hardness: 'Extremely Hard (4500 lbf Janka)',
    color_description: 'Greenish-brown to nearly black, with alternating light and dark bands',
    common_uses: ['Bearings', 'Mallets', 'Bowling balls', 'Pulleys', 'Propeller shaft bearings'],
    fun_fact: 'Lignum Vitae is the hardest commercially available wood in the world and contains so much natural resin it is self-lubricating — it was used for submarine propeller shaft bearings in WWII.',
    origin: 'Caribbean and South America',
    rot_resistant: true,
    keywords: ['green', 'dark', 'black', 'lignum vitae', 'hardest', 'dense', 'resinous', 'tropical'],
  },
  {
    species: 'Maclura pomifera',
    common_name: 'Osage Orange',
    confidence: 72,
    grain: 'Straight to interlocked, coarse',
    hardness: 'Extremely Hard (2040 lbf Janka)',
    color_description: 'Bright golden-yellow when fresh, fades to brown with UV exposure',
    common_uses: ['Fence posts', 'Archery bows', 'Tool handles', 'Turning', 'Dye production'],
    fun_fact: 'Osage Orange is the most rot-resistant wood native to North America — fence posts can last over 100 years in the ground without treatment.',
    origin: 'South-Central United States',
    rot_resistant: true,
    keywords: ['yellow', 'golden', 'bright', 'osage orange', 'hedge apple', 'coarse', 'dense'],
  },
  {
    species: 'Chlorophora excelsa',
    common_name: 'Iroko',
    confidence: 72,
    grain: 'Interlocked, medium to coarse',
    hardness: 'Hard (1260 lbf Janka)',
    color_description: 'Yellow-brown to medium brown, sometimes with calcium deposits',
    common_uses: ['Furniture', 'Flooring', 'Boat building', 'Veneer', 'Outdoor construction'],
    fun_fact: 'Iroko is often called "African Teak" because of its similar durability and appearance — it is a popular sustainable alternative to true Teak.',
    origin: 'West and East Africa',
    rot_resistant: true,
    keywords: ['yellow brown', 'medium brown', 'iroko', 'african teak', 'interlocked', 'coarse', 'tropical'],
  },
  {
    species: 'Microberlinia brazzavillensis',
    common_name: 'Zebrawood',
    confidence: 72,
    grain: 'Interlocked, coarse',
    hardness: 'Hard (1575 lbf Janka)',
    color_description: 'Pale golden-yellow with narrow dark brown to black stripes',
    common_uses: ['Veneer', 'Furniture accents', 'Turning', 'Inlays', 'Decorative panels'],
    fun_fact: 'Zebrawood\'s dramatic striping is caused by alternating bands of light parenchyma and dark fiber tissue — no two boards have exactly the same pattern.',
    origin: 'West Africa',
    rot_resistant: false,
    keywords: ['yellow', 'striped', 'black stripes', 'zebrawood', 'zebra', 'figured', 'tropical', 'dramatic'],
  },
  {
    species: 'Cordia elaeagnoides',
    common_name: 'Bocote',
    confidence: 72,
    grain: 'Straight to slightly wavy, medium',
    hardness: 'Hard (2010 lbf Janka)',
    color_description: 'Yellow-brown to golden with dramatic dark brown to black figure and streaks',
    common_uses: ['Furniture', 'Flooring', 'Turning', 'Knife handles', 'Musical instruments'],
    fun_fact: 'Bocote is one of the most visually striking woods in the world — its wild, graphic figure is caused by irregular growth patterns unique to each tree.',
    origin: 'Mexico and Central America',
    rot_resistant: true,
    keywords: ['golden', 'yellow brown', 'dark streaks', 'bocote', 'figured', 'dramatic', 'tropical', 'graphic'],
  },
  {
    species: 'Dalbergia retusa',
    common_name: 'Cocobolo',
    confidence: 72,
    grain: 'Straight to interlocked, fine',
    hardness: 'Very Hard (2960 lbf Janka)',
    color_description: 'Orange to deep red with irregular black streaks, highly variable',
    common_uses: ['Knife handles', 'Musical instruments', 'Turning', 'Jewelry', 'Fine furniture'],
    fun_fact: 'Cocobolo is so oily that glue barely adheres to it — woodworkers must wipe surfaces with acetone before gluing to remove the natural oils.',
    origin: 'Central America',
    rot_resistant: true,
    keywords: ['orange', 'red', 'black streaks', 'cocobolo', 'oily', 'fine grain', 'dense', 'tropical'],
  },

  // ── Specialty / Figured ──────────────────────────────────────────────────────
  {
    species: 'Acer saccharum var.',
    common_name: 'Figured Maple',
    confidence: 72,
    grain: 'Wavy, producing chatoyant figure',
    hardness: 'Very Hard (1450 lbf Janka)',
    color_description: 'Creamy white to light tan with shimmering three-dimensional figure',
    common_uses: ['Guitar tops', 'Fine furniture', 'Veneer', 'Violin backs', 'Decorative panels'],
    fun_fact: 'Figured Maple\'s chatoyant shimmer — called "flame" or "tiger" figure — is caused by wavy grain that reflects light differently at different angles.',
    origin: 'Eastern North America',
    rot_resistant: false,
    keywords: ['white', 'cream', 'figured', 'flame maple', 'tiger maple', 'chatoyant', 'wavy', 'shimmer'],
  },
  {
    species: 'Acer saccharum var.',
    common_name: 'Spalted Maple',
    confidence: 72,
    grain: 'Fine, straight with zone lines',
    hardness: 'Variable (partially decayed)',
    color_description: 'White to pale tan with dramatic black zone lines from fungal activity',
    common_uses: ['Turning', 'Decorative bowls', 'Furniture accents', 'Veneer', 'Art pieces'],
    fun_fact: 'Spalting is controlled decay — woodworkers deliberately expose maple logs to specific fungi, then kiln-dry them at exactly the right moment to preserve the dramatic patterns.',
    origin: 'Eastern North America',
    rot_resistant: false,
    keywords: ['white', 'black lines', 'zone lines', 'spalted', 'fungal', 'dramatic', 'maple', 'unique'],
  },
  {
    species: 'Juglans nigra var.',
    common_name: 'Crotch Walnut',
    confidence: 72,
    grain: 'Highly irregular, feather or plume figure',
    hardness: 'Hard (1010 lbf Janka)',
    color_description: 'Rich chocolate brown with dramatic feather-like figure at branch junctions',
    common_uses: ['Veneer', 'Fine furniture', 'Decorative panels', 'Jewelry boxes', 'Art pieces'],
    fun_fact: 'Crotch figure forms where a tree trunk splits into major branches — the compressed, swirling grain creates a feather or plume pattern worth many times plain walnut.',
    origin: 'Eastern North America',
    rot_resistant: true,
    keywords: ['dark brown', 'chocolate', 'feather figure', 'plume', 'crotch', 'walnut', 'figured', 'dramatic'],
  },
  {
    species: 'Quercus robur var.',
    common_name: 'Burr Oak Burl',
    confidence: 72,
    grain: 'Highly irregular, swirling burl figure',
    hardness: 'Hard (1120 lbf Janka)',
    color_description: 'Light to medium brown with swirling, eye-like burl patterns',
    common_uses: ['Veneer', 'Turning', 'Decorative bowls', 'Jewelry boxes', 'Art pieces'],
    fun_fact: 'Oak burls form as a response to stress — injury, disease, or insect infestation causes the tree to produce a mass of dormant buds that create the swirling grain.',
    origin: 'Europe, North America',
    rot_resistant: true,
    keywords: ['brown', 'burl', 'swirling', 'eyes', 'figured', 'oak', 'irregular', 'decorative'],
  },
  {
    species: 'Sequoia sempervirens',
    common_name: 'Redwood',
    confidence: 72,
    grain: 'Straight, coarse',
    hardness: 'Soft (450 lbf Janka)',
    color_description: 'Deep reddish-brown to pinkish-red, uniform and straight-grained',
    common_uses: ['Outdoor furniture', 'Decking', 'Siding', 'Fencing', 'Raised garden beds'],
    fun_fact: 'Coast Redwood is the tallest tree species on Earth — the tallest known individual, Hyperion, stands 380 feet tall and is estimated to be over 700 years old.',
    origin: 'California Coast, USA',
    rot_resistant: true,
    keywords: ['red', 'reddish brown', 'redwood', 'straight', 'coarse', 'outdoor', 'california'],
  },
  {
    species: 'Cedrus libani',
    common_name: 'Cedar of Lebanon',
    confidence: 72,
    grain: 'Straight, fine to medium',
    hardness: 'Soft (900 lbf Janka)',
    color_description: 'Pale pinkish-brown to reddish-brown, aromatic with visible resin canals',
    common_uses: ['Chests', 'Closet linings', 'Outdoor furniture', 'Pencils', 'Decorative woodwork'],
    fun_fact: 'Cedar of Lebanon was the most prized timber of the ancient world — King Solomon used it to build the First Temple in Jerusalem around 950 BCE.',
    origin: 'Middle East, Mediterranean',
    rot_resistant: true,
    keywords: ['pink', 'reddish brown', 'cedar', 'aromatic', 'soft', 'fine', 'resinous', 'pale'],
  },
  {
    species: 'Taxus baccata',
    common_name: 'English Yew',
    confidence: 72,
    grain: 'Straight to irregular, fine',
    hardness: 'Hard (1520 lbf Janka)',
    color_description: 'Orange-brown to reddish-brown heartwood with pale yellow sapwood',
    common_uses: ['Longbows', 'Furniture', 'Turning', 'Carving', 'Veneers'],
    fun_fact: 'English Yew was the wood of the English longbow — the combination of heartwood (compression) and sapwood (tension) in a single stave creates a natural composite spring.',
    origin: 'Europe, North Africa, Southwest Asia',
    rot_resistant: true,
    keywords: ['orange brown', 'reddish', 'yellow sapwood', 'yew', 'fine grain', 'hard', 'european'],
  },
  {
    species: 'Platanus occidentalis',
    common_name: 'American Sycamore',
    confidence: 72,
    grain: 'Interlocked, producing lace or fleck figure on quartersawn faces',
    hardness: 'Medium-Hard (770 lbf Janka)',
    color_description: 'Light to medium reddish-brown with distinctive ray fleck pattern',
    common_uses: ['Butcher blocks', 'Furniture', 'Veneer', 'Cabinetry', 'Musical instruments'],
    fun_fact: 'American Sycamore\'s quartersawn face reveals a spectacular lace-like ray fleck pattern — it was called "lacewood" by Victorian furniture makers who prized it for decorative panels.',
    origin: 'Eastern North America',
    rot_resistant: false,
    keywords: ['reddish brown', 'light brown', 'ray fleck', 'lace', 'sycamore', 'interlocked', 'figured'],
  },
];

/**
 * Check if the device currently has an internet connection.
 * Uses a HEAD request to Google with a 3-second timeout.
 */
export async function isOnline(): Promise<boolean> {
  console.log('[WoodEye] Checking network connectivity...');
  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => {
      console.log('[WoodEye] Network check timed out after 3s');
      controller.abort();
    }, 3000);

    const response = await fetch('https://www.google.com', {
      method: 'HEAD',
      signal: controller.signal,
    });
    clearTimeout(timeoutId);
    const online = response.ok || response.status < 500;
    console.log('[WoodEye] Network check result: online =', online, '(status', response.status, ')');
    return online;
  } catch (e: any) {
    console.log('[WoodEye] Network check failed (offline):', e?.message ?? e);
    return false;
  }
}

/**
 * Attempt to find a cached species match.
 * Without the actual image data we cannot do real visual matching,
 * so this always returns null — the offline UX handles the no-match case gracefully.
 */
export function findCachedMatch(_imageDescription?: string): CachedSpecies | null {
  console.log('[WoodEye] findCachedMatch called — returning null (no AI available offline)');
  return null;
}
